# Generated by Django 4.2.4 on 2023-08-08 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='약 이름')),
                ('image', models.ImageField(upload_to='', verbose_name='사진')),
                ('medi_info', models.TextField(max_length=2000, verbose_name='약물 정보')),
                ('url', models.URLField(default='', verbose_name='약햑정보원 바로가기')),
            ],
        ),
        migrations.CreateModel(
            name='Scrap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrap', to='posts.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrap', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
