# Generated by Django 4.2.3 on 2023-08-11 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.URLField(default='', verbose_name='사진'),
        ),
    ]
