# Generated by Django 4.2.4 on 2023-08-15 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='medi_info',
            field=models.TextField(verbose_name='약물 정보'),
        ),
    ]
