# Generated by Django 4.2.4 on 2023-08-15 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_medicine_allergy_medicine_disease_alter_allergy_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='allergy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allergy_medi', to='accounts.allergy'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='disease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disease_medi', to='accounts.disease'),
        ),
    ]
