# Generated by Django 4.2.4 on 2023-08-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_medicine_allergy_alter_medicine_disease'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='Ingredients_amount',
            field=models.TextField(default='', null=True, verbose_name='Ingredients_amount'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='classification',
            field=models.CharField(max_length=15, null=True, verbose_name='medi_classification'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='doping',
            field=models.BooleanField(default=False, verbose_name='doping'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='efficacy',
            field=models.CharField(max_length=30, null=True, verbose_name='efficacy'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='infomation',
            field=models.TextField(default='', null=True, verbose_name='infomation'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='order',
            field=models.IntegerField(default=0, null=True, verbose_name='number'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='storage',
            field=models.CharField(max_length=15, null=True, verbose_name='storage'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='usage',
            field=models.CharField(max_length=15, null=True, verbose_name='usage'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='warning',
            field=models.CharField(max_length=15, null=True, verbose_name='warning'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='name',
            field=models.CharField(max_length=15, null=True, verbose_name='medicine_name'),
        ),
    ]
